name: bmnav_null_safety
description: A highly flexible Flutter implementation of the Bottom Navigation Bar.
version: 1.0.0
homepage: https://github.com/aisivan36/bmnav_null_safety

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
